#ifndef RENDER_GL_DRIVER_GLX_ENTRIES_HEADER
#define RENDER_GL_DRIVER_GLX_ENTRIES_HEADER

#include <shared/profile/gl/glxext.h>

namespace render
{

namespace low_level
{

namespace opengl
{

//forward declaration
class ILibrary;

namespace glx
{

///////////////////////////////////////////////////////////////////////////////////////////////////
///Точки входа расширений GLX
///////////////////////////////////////////////////////////////////////////////////////////////////
struct GlxExtensionsEntries
{

  PFNGLXGETFBCONFIGSPROC GetFBConfigs;
  PFNGLXCHOOSEFBCONFIGPROC ChooseFBConfig;
  PFNGLXGETFBCONFIGATTRIBPROC GetFBConfigAttrib;
  PFNGLXGETVISUALFROMFBCONFIGPROC GetVisualFromFBConfig;
  PFNGLXCREATEWINDOWPROC CreateWindow;
  PFNGLXDESTROYWINDOWPROC DestroyWindow;
  PFNGLXCREATEPIXMAPPROC CreatePixmap;
  PFNGLXDESTROYPIXMAPPROC DestroyPixmap;
  PFNGLXCREATEPBUFFERPROC CreatePbuffer;
  PFNGLXDESTROYPBUFFERPROC DestroyPbuffer;
  PFNGLXQUERYDRAWABLEPROC QueryDrawable;
  PFNGLXCREATENEWCONTEXTPROC CreateNewContext;
  PFNGLXMAKECONTEXTCURRENTPROC MakeContextCurrent;
  PFNGLXGETCURRENTREADDRAWABLEPROC GetCurrentReadDrawable;
  PFNGLXGETCURRENTDISPLAYPROC GetCurrentDisplay;
  PFNGLXQUERYCONTEXTPROC QueryContext;
  PFNGLXSELECTEVENTPROC SelectEvent;
  PFNGLXGETSELECTEDEVENTPROC GetSelectedEvent;
  PFNGLXGETPROCADDRESSPROC GetProcAddress;
  PFNGLXGETPROCADDRESSARBPROC GetProcAddressARB;
  PFNGLXCREATECONTEXTATTRIBSARBPROC CreateContextAttribsARB;
  PFNGLXSWAPINTERVALSGIPROC SwapIntervalSGI;
  PFNGLXGETVIDEOSYNCSGIPROC GetVideoSyncSGI;
  PFNGLXWAITVIDEOSYNCSGIPROC WaitVideoSyncSGI;
  PFNGLXMAKECURRENTREADSGIPROC MakeCurrentReadSGI;
  PFNGLXGETCURRENTREADDRAWABLESGIPROC GetCurrentReadDrawableSGI;
//  PFNGLXCREATEGLXVIDEOSOURCESGIXPROC CreateGLXVideoSourceSGIX;
//  PFNGLXDESTROYGLXVIDEOSOURCESGIXPROC DestroyGLXVideoSourceSGIX;
  PFNGLXGETCURRENTDISPLAYEXTPROC GetCurrentDisplayEXT;
  PFNGLXQUERYCONTEXTINFOEXTPROC QueryContextInfoEXT;
  PFNGLXGETCONTEXTIDEXTPROC GetContextIDEXT;
  PFNGLXIMPORTCONTEXTEXTPROC ImportContextEXT;
  PFNGLXFREECONTEXTEXTPROC FreeContextEXT;
  PFNGLXGETFBCONFIGATTRIBSGIXPROC GetFBConfigAttribSGIX;
  PFNGLXCHOOSEFBCONFIGSGIXPROC ChooseFBConfigSGIX;
  PFNGLXCREATEGLXPIXMAPWITHCONFIGSGIXPROC CreateGLXPixmapWithConfigSGIX;
  PFNGLXCREATECONTEXTWITHCONFIGSGIXPROC CreateContextWithConfigSGIX;
  PFNGLXGETVISUALFROMFBCONFIGSGIXPROC GetVisualFromFBConfigSGIX;
  PFNGLXGETFBCONFIGFROMVISUALSGIXPROC GetFBConfigFromVisualSGIX;
  PFNGLXCREATEGLXPBUFFERSGIXPROC CreateGLXPbufferSGIX;
  PFNGLXDESTROYGLXPBUFFERSGIXPROC DestroyGLXPbufferSGIX;
  PFNGLXQUERYGLXPBUFFERSGIXPROC QueryGLXPbufferSGIX;
  PFNGLXSELECTEVENTSGIXPROC SelectEventSGIX;
  PFNGLXGETSELECTEDEVENTSGIXPROC GetSelectedEventSGIX;
  PFNGLXCUSHIONSGIPROC CushionSGI;
  PFNGLXBINDCHANNELTOWINDOWSGIXPROC BindChannelToWindowSGIX;
  PFNGLXCHANNELRECTSGIXPROC ChannelRectSGIX;
  PFNGLXQUERYCHANNELRECTSGIXPROC QueryChannelRectSGIX;
  PFNGLXQUERYCHANNELDELTASSGIXPROC QueryChannelDeltasSGIX;
  PFNGLXCHANNELRECTSYNCSGIXPROC ChannelRectSyncSGIX;
//  PFNGLXASSOCIATEDMPBUFFERSGIXPROC AssociateDMPbufferSGIX;
  PFNGLXJOINSWAPGROUPSGIXPROC JoinSwapGroupSGIX;
  PFNGLXBINDSWAPBARRIERSGIXPROC BindSwapBarrierSGIX;
  PFNGLXQUERYMAXSWAPBARRIERSSGIXPROC QueryMaxSwapBarriersSGIX;
  PFNGLXGETTRANSPARENTINDEXSUNPROC GetTransparentIndexSUN;
  PFNGLXCOPYSUBBUFFERMESAPROC CopySubBufferMESA;
  PFNGLXCREATEGLXPIXMAPMESAPROC CreateGLXPixmapMESA;
  PFNGLXRELEASEBUFFERSMESAPROC ReleaseBuffersMESA;
  PFNGLXSET3DFXMODEMESAPROC Set3DfxModeMESA;
  PFNGLXGETSYNCVALUESOMLPROC GetSyncValuesOML;
  PFNGLXGETMSCRATEOMLPROC GetMscRateOML;
  PFNGLXSWAPBUFFERSMSCOMLPROC SwapBuffersMscOML;
  PFNGLXWAITFORMSCOMLPROC WaitForMscOML;
  PFNGLXWAITFORSBCOMLPROC WaitForSbcOML;
  PFNGLXQUERYHYPERPIPENETWORKSGIXPROC QueryHyperpipeNetworkSGIX;
  PFNGLXHYPERPIPECONFIGSGIXPROC HyperpipeConfigSGIX;
  PFNGLXQUERYHYPERPIPECONFIGSGIXPROC QueryHyperpipeConfigSGIX;
  PFNGLXDESTROYHYPERPIPECONFIGSGIXPROC DestroyHyperpipeConfigSGIX;
  PFNGLXBINDHYPERPIPESGIXPROC BindHyperpipeSGIX;
  PFNGLXQUERYHYPERPIPEBESTATTRIBSGIXPROC QueryHyperpipeBestAttribSGIX;
  PFNGLXHYPERPIPEATTRIBSGIXPROC HyperpipeAttribSGIX;
  PFNGLXQUERYHYPERPIPEATTRIBSGIXPROC QueryHyperpipeAttribSGIX;
  PFNGLXGETAGPOFFSETMESAPROC GetAGPOffsetMESA;
  PFNGLXBINDTEXIMAGEEXTPROC BindTexImageEXT;
  PFNGLXRELEASETEXIMAGEEXTPROC ReleaseTexImageEXT;
  PFNGLXENUMERATEVIDEODEVICESNVPROC EnumerateVideoDevicesNV;
  PFNGLXBINDVIDEODEVICENVPROC BindVideoDeviceNV;
  PFNGLXGETVIDEODEVICENVPROC GetVideoDeviceNV;
  PFNGLXRELEASEVIDEODEVICENVPROC ReleaseVideoDeviceNV;
  PFNGLXBINDVIDEOIMAGENVPROC BindVideoImageNV;
  PFNGLXRELEASEVIDEOIMAGENVPROC ReleaseVideoImageNV;
  PFNGLXSENDPBUFFERTOVIDEONVPROC SendPbufferToVideoNV;
  PFNGLXGETVIDEOINFONVPROC GetVideoInfoNV;
  PFNGLXJOINSWAPGROUPNVPROC JoinSwapGroupNV;
  PFNGLXBINDSWAPBARRIERNVPROC BindSwapBarrierNV;
  PFNGLXQUERYSWAPGROUPNVPROC QuerySwapGroupNV;
  PFNGLXQUERYMAXSWAPGROUPSNVPROC QueryMaxSwapGroupsNV;
  PFNGLXQUERYFRAMECOUNTNVPROC QueryFrameCountNV;
  PFNGLXRESETFRAMECOUNTNVPROC ResetFrameCountNV;
  PFNGLXBINDVIDEOCAPTUREDEVICENVPROC BindVideoCaptureDeviceNV;
  PFNGLXENUMERATEVIDEOCAPTUREDEVICESNVPROC EnumerateVideoCaptureDevicesNV;
  PFNGLXLOCKVIDEOCAPTUREDEVICENVPROC LockVideoCaptureDeviceNV;
  PFNGLXQUERYVIDEOCAPTUREDEVICENVPROC QueryVideoCaptureDeviceNV;
  PFNGLXRELEASEVIDEOCAPTUREDEVICENVPROC ReleaseVideoCaptureDeviceNV;
  PFNGLXSWAPINTERVALEXTPROC SwapIntervalEXT;
  PFNGLXCOPYIMAGESUBDATANVPROC CopyImageSubDataNV;
  
///////////////////////////////////////////////////////////////////////////////////////////////////
///Инициализация точек входа
///////////////////////////////////////////////////////////////////////////////////////////////////
  void Init (ILibrary&);
};

}

}

}

}

#endif
