TARGETS := MATH.CURVES.SOURCES MATH.CURVES.TESTS

MATH.CURVES.SOURCES.TYPE        := static-lib
MATH.CURVES.SOURCES.NAME        := funner.math.curves
MATH.CURVES.SOURCES.SOURCE_DIRS := sources
MATH.CURVES.SOURCES.IMPORTS     :=

MATH.CURVES.TESTS.TYPE        := test-suite
MATH.CURVES.TESTS.SOURCE_DIRS := tests
MATH.CURVES.TESTS.IMPORTS     := 
