#ifndef RENDER_GL_DRIVER_GL_PROFILE_HEADER
#define RENDER_GL_DRIVER_GL_PROFILE_HEADER

#include <shared/profile/gl/gl_types.h>
#include <shared/profile/gl/glext.h>
#include <shared/profile/gl/entries.h>

/*
    ѕереопределени€ дл€ упрощени€ портируемости
*/

typedef PFNGLISRENDERBUFFEREXTPROC                      PFNGLISRENDERBUFFERPROC;
typedef PFNGLBINDRENDERBUFFEREXTPROC                    PFNGLBINDRENDERBUFFERPROC;
typedef PFNGLDELETERENDERBUFFERSEXTPROC                 PFNGLDELETERENDERBUFFERSPROC;
typedef PFNGLGENRENDERBUFFERSEXTPROC                    PFNGLGENRENDERBUFFERSPROC;
typedef PFNGLRENDERBUFFERSTORAGEEXTPROC                 PFNGLRENDERBUFFERSTORAGEPROC;
typedef PFNGLGETRENDERBUFFERPARAMETERIVEXTPROC          PFNGLGETRENDERBUFFERPARAMETERIVPROC;
typedef PFNGLISFRAMEBUFFEREXTPROC                       PFNGLISFRAMEBUFFERPROC;
typedef PFNGLBINDFRAMEBUFFEREXTPROC                     PFNGLBINDFRAMEBUFFERPROC;
typedef PFNGLDELETEFRAMEBUFFERSEXTPROC                  PFNGLDELETEFRAMEBUFFERSPROC;
typedef PFNGLGENFRAMEBUFFERSEXTPROC                     PFNGLGENFRAMEBUFFERSPROC;
typedef PFNGLCHECKFRAMEBUFFERSTATUSEXTPROC              PFNGLCHECKFRAMEBUFFERSTATUSPROC;
typedef PFNGLFRAMEBUFFERRENDERBUFFEREXTPROC             PFNGLFRAMEBUFFERRENDERBUFFERPROC;
typedef PFNGLFRAMEBUFFERTEXTURE1DEXTPROC                PFNGLFRAMEBUFFERTEXTURE1DPROC;
typedef PFNGLFRAMEBUFFERTEXTURE2DEXTPROC                PFNGLFRAMEBUFFERTEXTURE2DPROC;
typedef PFNGLFRAMEBUFFERTEXTURE3DEXTPROC                PFNGLFRAMEBUFFERTEXTURE3DPROC;
typedef PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVEXTPROC PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC;

#define GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_EXT
#define GL_FRAMEBUFFER_INCOMPLETE_FORMATS    GL_FRAMEBUFFER_INCOMPLETE_FORMATS_EXT

#endif
