TARGETS := MATH.VECMATH.TESTS

MATH.VECMATH.TESTS.TYPE         := test-suite
MATH.VECMATH.TESTS.INCLUDE_DIRS := include
MATH.VECMATH.TESTS.SOURCE_DIRS  := tests
MATH.VECMATH.TESTS.msvc.COMPILER_DEFINES := VECMATH_SSE
MATH.VECMATH.TESTS.msvc.COMPILER_CFLAGS  := -arch:SSE
#MATH.VECMATH.TESTS.msvc.COMPILER_CFLAGS += -Fa
