TARGETS := MATH.VECMATH.TESTS

MATH.VECMATH.TESTS.TYPE         := test-suite
MATH.VECMATH.TESTS.SOURCE_DIRS  := tests
MATH.VECMATH.TESTS.IMPORTS      := compile.math.vecmath
#MATH.VECMATH.TESTS.msvc.COMPILER_CFLAGS += -Fa
